# This is a basic workflow to help you get started with Actions

name: CI_TESTBRANCH

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - '*'
      - '!master'
  pull_request:
    branches:
      - '*'
      - '!master'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_testbranch:
    # The type of runner that the job will run on
    runs-on: windows-2019
  
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell
      # Support longpaths
      - name: Support long paths
        run: git config --system core.longpaths true
      
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with: 
          fetch-depth: '1'

      # Runs a set of commands using the runners shell
      - name: Build JCOReflectorCLI
        run: |
          dotnet build --no-incremental --framework netcoreapp3.1 JCOReflector\JCOReflectorCLI.sln
          dotnet build --no-incremental --framework net461 JCOReflector\JCOReflectorCLI.sln  

      # Runs a set of commands using the runners shell
      - name: Copy configuration file
        run: Copy-Item .github\workflows\JCOReflectorCLI.runtimeconfig.json -Destination bin\netcoreapp3.1\JCOReflectorCLI.runtimeconfig.json -Force

      - name: Remove Java files
        run: |
          Remove-Item .\netreflected\src\netcoreapp3.1 -Recurse -Force 
          Remove-Item .\netreflected\src\net461 -Recurse -Force
          
      - name: Reflect .NET Core 3.1 Java files
        run:
          dotnet bin\netcoreapp3.1\JCOReflectorCLI.dll reflect .github\workflows\reflect_netcoreapp3.1.job
          
      - name: Reflect .NET Framework Java files
        run:
          .\bin\net461\JCOReflectorCLI reflect .github\workflows\reflect_net461.job
          
      - name: Build Java files
        run: |
          dotnet bin\netcoreapp3.1\JCOReflectorCLI.dll build .github\workflows\build_win19.job
          .\bin\net461\JCOReflectorCLI build .github\workflows\build_win19.job
